version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8008:80"
        volumes:
            - ./www:/var/www/html
        links:
            -   db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - 3306:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: test
#        networks:
#            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_ROOT_PASSWORD: test
